### ISSUE TITLE
ColumnNames with underline "_"-Character not resolved properly when working with GridProcessingMode.Manual  

### ISSUE THREAD

**Issue by sgraf-wega** [NonFactors/AspNetCore.Grid#225]
For example: a columnname  "**MDM_Master**" will be submitted as "**m-d-m-master**" in query-get-parameter when GridHeader (sorting) is clicked.  This is probably caused by the regular expression in **GridColumnExtensions.Named** -Method. 
Since this expression replaces any underline by an "-" Character, it ist not possible to derive the original backend-columnname and the link-query crashes with "mdmmaster" is not a valid property. 
As a workaround it is possible to map known columnnames which contains an underline
inside Controller-Method Index(int? page, string **sort**, string order) to the original name but i think it is better, to keep the underline a valid character in columnname .  It is a usual character in  (for example) sqlserver-columnnames.

**Comment by Muchiachio** [comment]
You can specify any name using `.Named` function. You can also wrap that into your own `.AddColumn` extension, which would apply your defaults.

They are replaced like that for user friendly urls :frowning_face: Guess no one cares about that so we should just leave the member expression as is and whoever wants to change it will have to write they own extension.
