### ISSUE TITLE
Attributes in columns

### ISSUE THREAD

**Issue by DanielStaroscik** [NonFactors/AspNetCore.Grid#235]
Hi!
It is possible to add "Attributed(object htmlAttributes)" method to GridColumn like it is on HtmlGrid?

In my case I'm trying to combine toogether MVC Grid with KonkoutJS and I need to add ssome html attributest to `<td>` elements.

**Comment by Muchiachio** [comment]
This might be possible in the next grid version as I'm trying to remove html from the grid partial.
No promises though. You can always make a custom grid column class with the necessary fields and use that with your custom grid partial.
```C#
public interface IAttributedGridColumn
{
    GridHtmlAttributes Attributes { get; set; }
}

public class MyGridColumn<T, TValue> : GridColumn<T, TValue>, IAttributedGridColumn where T : class
{
    public GridHtmlAttributes Attributes { get; set; }

    public MyGridColumn(IGrid<T> grid, Expression<Func<T, TValue>> expression)
        : base(grid, expression)
    {
        Attributes = new GridHtmlAttributes();
    }
}
```
creating columns with your own extension
```C#
public static MyGridColumn<T, TValue> AddColumn<T, TValue>(this IGridColumnsOf<T> columns, Expression<Func<T, TValue>> expression) where T : class
{
    MyGridColumn<T, TValue> column = new MyGridColumn<T, TValue>(columns.Grid, expression);
    (columns as GridColumns<T>).Add(column);
    column.Grid.Processors.Add(column);

    return column;
}
```
similar extension for attributed or event pass it as a parameter and render it in the partial.
