### ISSUE TITLE
Displaying dynamic column to grid

### ISSUE THREAD

**Issue by anantjaiswal339** [NonFactors/AspNetCore.Grid#237]
I was displaying dynamic column as below that was working perfectly but when the header name is duplicate for different contact then instead of adding column for that it should display row value in same column for another contact also
> Sample Data For Dynamic Column

```
List<ContactCustomFieldViewModel> contactCustomField = new List<ContactCustomFieldViewModel>();
contactCustomField.Add(new ContactCustomFieldViewModel { ContactID = new Guid("70790767-2b1e-4a43-af05-b9402ecae4ef"), FieldLabel = "Custom1", CustomFieldValue = "value1" });
contactCustomField.Add(new ContactCustomFieldViewModel { ContactID = new Guid("70790767-2b1e-4a43-af05-15e64688222"), FieldLabel = "Custom1", CustomFieldValue = "value1.1" });
contactCustomField.Add(new ContactCustomFieldViewModel { ContactID = new Guid("70790767-2b1e-4a43-af05-15e64688333"), FieldLabel = "Custom1", CustomFieldValue = "value11.2" });
contactCustomField.Add(new ContactCustomFieldViewModel { ContactID = new Guid("0c1f5526-036a-4ed4-a500-b1cd02e99fe7"), FieldLabel = "Custom2", CustomFieldValue = "value2" });
contactCustomField.Add(new ContactCustomFieldViewModel { ContactID = new Guid("15e64688-9e40-40dc-88df-14fa810326e4"), FieldLabel = "Custom3", CustomFieldValue = "value3" });
```
>Grid View
```
columns.Add(model => model.TotalSpent).Titled("TotalSpent");

foreach (var item in CustomField)
{
    columns.Add(model => model.ContactID).RenderedAs(x => x.ContactID == item.ContactID ? item.CustomFieldValue : "").Titled(item.FieldLabel);
}
```
https://www.screencast.com/t/WrL4JtBJUDdi
Hope I'm able to explain my issue

**Comment by Muchiachio** [comment]
You are most likely running into [a loop closure problem](https://stackoverflow.com/questions/271440/captured-variable-in-a-loop-in-c-sharp) as you are using `foreach` variable in a lambda.

**Comment by anantjaiswal339** [comment]
Yes, because that custom column is dynamic there can be multiple.
But the thing is suppose there is DOB column that is in list as above with contactid so how can I do that only one DOB column should be added and value will be display respectively to contact.

**Comment by Muchiachio** [comment]
Shouldn't `CustomField` be a dictionary with `ContactId => value` map, so you can use only one column?

**Comment by anantjaiswal339** [comment]
Actually, `CustomField` will be in different dictionary as technically this is coming from another table,
Even I can add particular custom field to Contact lists by loop but we have more than lac contacts that may slow the system.

**Comment by anantjaiswal339** [comment]
Do we have any way to add all the dynamic column first then bind the value by particular row

**Comment by Muchiachio** [comment]
This is how it works now, you create column declarations and for every row it tries to get the value specified in `.Add` or `.RenderedAs` methods.

**Comment by anantjaiswal339** [comment]
Yes, but as per my above list it adds multiple header.
https://www.screencast.com/t/i50epjTrJ

**Comment by Muchiachio** [comment]
Well you are adding multiple columns, you can do any checks on your models to not add them :?

**Comment by anantjaiswal339** [comment]
actually I have model but as per software feature we require to add dynamic column that is beyond to model and where title and value can anything.
For instance this is my add contact UI to add custom/dynamic column with value : https://www.screencast.com/t/2wcvQSrpBss

Now I have to add these in each row by checking contact Id.

**Comment by Muchiachio** [comment]
You can't add columns while iterating rows. It's the same in html you have to know columns in advance.
