### ISSUE TITLE
Why it failed to use page size "All" if rows count is more than 100

### ISSUE THREAD

**Issue by maodean001** [NonFactors/AspNetCore.Grid#238]
I have 543 rows to display. If I set the rows per page is 10 or 20, it works perfectly. However, if I use "All", it failed. And if I set rows per page is 100, it also failed. is there any bug/limitation for this feature? thanks,

**Comment by Muchiachio** [comment]
There shouldn't be, can you share a repro or at least an exception you are getting?

**Comment by maodean001** [comment]
yes, sorry, its caused by some database error. sorry. I will close this one.
