### ISSUE TITLE
Aspnet Core MVC 2.1

### ISSUE THREAD

**Issue by gobinathpandi** [NonFactors/AspNetCore.Grid#239]
I followed your steps in your github site.
But, my Index page is refreshing each and every 3 secs.. I analyzed through chrome deveoper tools network tab, it shows that mvc-grid.js is intiating this page reloading for every x secs. Any help?

**Comment by Muchiachio** [comment]
Does your grid dll version match the static file version?

**Comment by gobinathpandi** [comment]
Yes, i copied from your github site.

**Comment by gobinathpandi** [comment]
https://github.com/NonFactors/AspNetCore.Grid/tree/develop/src/Mvc.Grid

I have copied statis assets from here.

**Comment by Muchiachio** [comment]
Installation notes don't mention using github files at all, current github files are for `v6.0.0`.
Dll's for that are not available as nugets unless you compiled the sources yourself.

**Comment by gobinathpandi** [comment]
Where i can find versioned static files. If i install nuget packages it should be auto generated in my project root. But, it doesnt happened.

**Comment by Muchiachio** [comment]
They don't generated because nuget stopped doing that in asp net core.
Static file locations are written out in [installation notes](https://mvc6-grid.azurewebsites.net/Home/Installation).

**Comment by gobinathpandi** [comment]
Okay, i look into this locations and let you know!

**Comment by gobinathpandi** [comment]
Closing this ticket,
This is not an issue.
