### ISSUE TITLE
Embed Static Files

### ISSUE THREAD

**Issue by jhr007** [NonFactors/AspNetCore.Grid#240]
FWIW 
Instead of having users copy files from the packages folder, you could embed them. 

The NSwag packages adds middleware to do this
https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.AspNetCore/Extensions/NSwagApplicationBuilderExtensions.cs#L77

Embeds the files here:
https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.AspNetCore/NSwag.AspNetCore.csproj#L33

**Comment by jhr007** [comment]
Now that I've got a working Grid, this probably only make sense for the .js file. 
I can see the cshtml and css files being customized.

**Comment by Muchiachio** [comment]
Yes, was thinking what will happen if people want to change or copy the partial for use.

**Comment by jhr007** [comment]
From a first time installer’s perspective, 
there’s definitely value in making it easier to get to a new grid that says “Hello world.” A simple grid is just the beginning of tweaking, I’ve been spending time adding a multi select,  adding a datepicker/filter, adding a filter for a first+last name column.

To me, It’s easier to have instructions that say install Nuget package, then add `app.AddMvcGridDefaults(opts => opts.someOpt=someval)` And then instructions that say add links to  .css and .js.
“ Now that you want to override styles/partials” copy the contents of files: (link to css/partials  file in current version)

I don’t have a  packager’s example of adding partials to the resource. But, You already provide an easy override for partials for both the grid and pager. 

Just kinda thinking out loud with this post. 

I’ll post my jquery datepicker next week that uses the current js class override.

**Comment by Muchiachio** [comment]
Well my idea was to never change js, css or the partial file directly. I think it's a bad practice to do that. Nuget used to give warnings when you modified package provided resources which was nice.

Imagine you changed something in any of those files and after some time you or someone else comes to upgrade the library version and just copies everything over (even looking at the diff might not be enough to notice that there were non library changes in there) resulting in something potentially not working. Therefore it's better to have `overrides.<library>.css` or similar to tell others explicitly that changes are done to the library "check if they are working with the next upgrade".

Css - can be easily overwritten with more specific styling.
Js - usually configurable options are enough, might use direct prototype extension for deep changes.
Partial - a copy in shared views being used through `.Grid(<partial>, source)` extension is recommended, which in site wide change can be hidden in a `.MyGrid(source)` extension to not copy over the partial name every time.

Theoretically it's possible to copy files into the project, but aspnetcore no longer has predefined project  structure, even wwwroot path can be replaced. Most of the people would still need to copy files over into their output directories, be it `js/dist`, `Scripts`, `public_html/js`, `static_cdn` or `css` folders. So I was putting it away for all this time 😕

Also, does embedding work with resource including, bundling and minification in production?
