### ISSUE TITLE
Compadibility with .Net Core 3.1

### ISSUE THREAD

**Issue by danielmertens** [NonFactors/AspNetCore.Grid#243]
Currently we are performing an upgrade on our Asp.Net Core 2.2 project to Asp.Net Core 3.1. After following all steps on the [migration document](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30) we noticed that the pages with MVCGrid are only being rendered up to the start of the grid. All components before it are loaded correctly but the grid and anything after isn't.

I have also tested this with a blank Asp.Net Core 3.1 project. The effect can be reproduced using this example:

```
@page
@using NonFactors.Mvc.Grid;
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
<div>
    Div before | This is shown on the page
</div>
@Html.Grid(Model.testStrings).Build(columns => columns.Add(model => model))
<div>
    Div after | This and the grid is not shown on the page 
</div>
```

Is there a solution for this behaviour or will we need to wait for a new version of AspNetCor.Grid?

Thank you in advance

**Comment by Muchiachio** [comment]
You might be running into issue [this](https://github.com/NonFactors/AspNetCore.Grid/issues/227) or similar, there should be an error visible in asp net core log.

**Comment by danielmertens** [comment]
That was indeed the issue. Thank you for your quick response.
