### ISSUE TITLE
Adding extra request headers in ajax grid

### ISSUE THREAD

**Issue by gobinathpandi** [NonFactors/AspNetCore.Grid#244]
Hi, How i can add extra header in grid reload!

**Comment by Muchiachio** [comment]
There is no built in way to do that, you would have to change `MvcGrid.prototype.startLoading` to add [them](https://github.com/NonFactors/AspNetCore.Grid/blob/v5.1.2/src/Mvc.Grid/js/mvc-grid/mvc-grid.js#L279). Can you share your use case for headers so we can try solving it in the next release?

**Comment by gobinathpandi** [comment]
I want to send csrf token in request header.

**Comment by Muchiachio** [comment]
You don't really need those on get requests, and it's weird if you are using grid with post/etc.

**Comment by gobinathpandi** [comment]
Get or Post both are http request. I need to add csrf custom token in header.

**Comment by Muchiachio** [comment]
Yes, but by default grid uses `get` and doesn't change state so there is nothing to protect.
