### ISSUE TITLE
get Current page 

### ISSUE THREAD

**Issue by sreelulaks** [NonFactors/AspNetCore.Grid#245]
Hello, Thank you for awesome grid for aspnet core. 

Could you please guide me how to get the current page of the grid? i have 1000's of records and retrieving only 100 at a time and also i am using custom pagination. The only one i am missing here is how to find on which page number user clicked and number of rows in the page. 

In my JQuery i am using to get the grid control
 var grid = new MvcGrid(document.querySelector('.mvc-grid'));

but from grid object how to get the Page Number and selected rows in page please?

Thanks,
Anu.

**Comment by Muchiachio** [comment]
You can inspect `MvcGrid` instance, it has `pager` property with the data.

**Comment by sreelulaks** [comment]
Thank you so much for quick response. Sorry just to be clear -

I need to call a controller from my razor page, up on clicking on the next/previous buttons on the pagination and send pagination details to fetch records from the API. 

Could you please guide if we have a documentation how to implement.

**Comment by Muchiachio** [comment]
Does [ajax](https://mvc6-grid.azurewebsites.net/Grid/Ajax) grid not do that for you? You can combine it with (manual pagination(https://mvc6-grid.azurewebsites.net/Grid/ManualProcessing) if needed. No need to change anything on the client side.

**Comment by sreelulaks** [comment]
You are awesome and genius. Thank you so much i got it. You made my day.

**Comment by sreelulaks** [comment]
I am sorry, was testing my grid and found a new issue with the manual Pagination, my grid is not sortable or searchable.

Here is my code, if i comment out the manual Pagination then it works. suggestion please?
@(Html.Grid(Model)
      .Build(columns =>
      {
          columns.Add(model => model.BankId);
          columns.Add(model => model.BankName).Filterable(true);
          columns.Add(model => model.BankAddress1).Filterable(true);          
      })
      .Empty("No data found")
      .Sortable()
     **// .UsingProcessingMode(GridProcessingMode.Manual)**
      .Pageable(pager =>
      {
          //pager.PartialViewName = "_MyCustomPager";
          pager.PageSizes = new Dictionary<Int32, String> { { 0, "All" }, { 100, "100" }, { 500, "500" } };
          pager.ShowPageSizes = true;
          //pager.TotalRows = ViewBag.TotalRows ?? 0;
          //pager.RowsPerPage = 100;
      })

**Comment by Muchiachio** [comment]
Manual processing implies you doing the filtering, searching and paging, because you are using hand written queries which grid can't generate queries for.

**Comment by sreelulaks** [comment]
Got you. 
So i can able to achieve the pagination but could you please direct me how to get the search & sorting? Can i call an action method up on search or sorting click? any documentation please?

**Comment by Muchiachio** [comment]
Easiest would be to make a [global search](https://mvc6-grid.azurewebsites.net/Grid/GlobalSearch), sort is available through `sort` and `order` parameters, similar to paging.

**Comment by sreelulaks** [comment]
Thank you i got the sort working. i have still issues with search, as this is global and i have 10 columns fetching it from api? how to filter? i see in the code you have provided 'repository.Filter(search)' but what is repository. i have a List object returns from the controller.

**Comment by Muchiachio** [comment]
I'm not sure how you get your data, but search is just a string u entered, so you can filter any way.
In the example it's just linq `.Where(model => model.Name.Contains(search) || ...)` and so on.

**Comment by sreelulaks** [comment]
Sorry for late response i realized after my question and sorted out thank you so much.
