### ISSUE TITLE
Ajax grid call firing multiple times on some pages

### ISSUE THREAD

**Issue by RichJohnsone** [NonFactors/AspNetCore.Grid#248]
Hi, I have an ajax grid that fires multiple calls when going to some pages - which cause an net::ERR_CONNECTION_RESET error. 

The grid is called by this line: `@Html.AjaxGrid(Url.Page("SiteMonitorGrid"), new { id = "sitesTable" })`

JS to set the grid up:          
```JS
var urlParams = new URLSearchParams(window.location.search);
var page = urlParams.get('page');
var rows = urlParams.get('rows');
var element = document.querySelector('.mvc-grid');
var options = {
    query: 'page=' + page + '&rows=' + rows
};
var grid = new MvcGrid(element, options);

grid.request.onloadstart = function (e) {
    $('.gridDiv')
        .innerHtml(
            '<div class="loadingDiv" style="margin:auto; height:100%; width:100%;"><h4 style="padding: 100px;">Grid loading ...</h4></div>');
};

grid.request.onloadend = function (e) {
    clearLoadingDiv();
};
```

I've checked in debug that the JS setup only gets hit once but my controller method in the backend gets hit three times, causing the error.

As the JS is only getting hit once i can't figure out a way around this.

**Comment by Muchiachio** [comment]
You can check F12 (Network tab) which call stacks are hitting your API.

**Comment by RichJohnsone** [comment]
Hi, sorry for the delayed response, I've been out of the office.

This is the network page for a successful call from the Grid, which hits the back-end web-service only once:
![SuccessfulCall](https://user-images.githubusercontent.com/22589975/73736318-7e3eb180-4738-11ea-9d28-9acd017d7024.PNG)

This is the network page and console from an unsuccessful call, which hits the JS once, but the web-service twice, causing the error:
![Unsuccessfulcall](https://user-images.githubusercontent.com/22589975/73736337-84cd2900-4738-11ea-85bb-d359011a85ff.PNG)

If I call the web-service directly from Postman it works almost instantly for both calls.

**Comment by Muchiachio** [comment]
Seems like one of those [weird asp net things](https://github.com/NonFactors/AspNetCore.Grid/issues/54) with `ERR_CONNECTION_RESET`
The error itself should be visible in [console log or enabling server log in web config](https://stackoverflow.com/questions/41489674/net-core-web-api-call-err-connection-reset-only-on-iis-other-calls-working).

**Comment by RichJohnsone** [comment]
wow this issue is really sucking in a lot of time. It's a deal-breaker for me - this grid is an essential core feature of my website. Sadly the links above did not proffer a solution.

**Comment by RichJohnsone** [comment]
Hi, I tried commenting the columns out one by one and loading the problem page. It turns out a recent change was throwing an un-handled error in a particular column for the data in the problem page. Why that led to a second, identical call to the web-service - I am still not sure, but at least my grid loads now and I can release the fix to my site. Thanks for your help.
