### ISSUE TITLE
How to get the grid query after filters in the footer

### ISSUE THREAD

**Issue by firstdivision** [NonFactors/AspNetCore.Grid#249]
In an Ajax grid with paging enabled, I'm trying to show the total count of **all** results (not just the rows shown on screen), and the average age across all results. But I can't figure out how to get at the query after any grid filters have been applied.

This is what I have now.  It works before any filters are applied, but not with filters applied.  For example, if I filter the grid's `Year Manufactured` column to display only cars manufactured after a certain date, the average age in my example footer below will stay the same.

I did see that there's another property called `Query` that appears to have the selected filters in it, but I don't know if there's a way to "apply" those to the `Source`?

**CarGridFooter.cshtml**
```CSHTML
@model IGrid<Shared.ViewModels.Car>

<tr>
    <td colspan="@Model.Columns.Count()">

        # of Results: @Model.Source.Count().ToString("#,###")
        Avg Age: @(Model.Source.Average(row => row.Age).ToString("#"))

    </td>
</tr>
```

**Comment by firstdivision** [comment]
I realized I can get to the full row count via the pager property (`@Model.Pager.TotalRows`), so now I just need to get at the average age.

**Comment by Muchiachio** [comment]
`@Model.Rows` contains the current page data, source is all data you passed to the grid.

**Comment by firstdivision** [comment]
Does that mean there is no way to get at the `Source` `IQueryable` after it has manifested (with any Grid filters applied)?

**Comment by Muchiachio** [comment]
With only filters and without paging, no.

**Comment by alamsor** [comment]
Not sure if this answers the question, but I was able to get an IQueryable after filters applied and its corresponding list with:
@Model.Rows.AsQueryable().ToList()

Are there any issues with this @Muchiachio ?
Thanks!

**Comment by Muchiachio** [comment]
@alamsor `Model.Rows` as mentioned in this [comment](https://github.com/NonFactors/AspNetCore.Grid/issues/249#issuecomment-583706184) contains only current page data, OP needed filtered data but without paging applied which is only available by applying filtering processors by hand.
```C#
IQueryable<T> items = Model.Source;

foreach (IGridProcessor<T> processor in (Model as IGrid<T>).Processors.Where(proc => proc.ProcessorType == GridProcessorType.Pre))
    items = processor.Process(items);
```
