### ISSUE TITLE
Any way to move paging to top of grid?

### ISSUE THREAD

**Issue by flgatormike** [NonFactors/AspNetCore.Grid#250]
Hi, I had a question that isn't really an issue. I would like to move the paging to the top of the grid. I thought I could just move this (inside _Grid.cshtml):
@await Html.PartialAsync(Model.Pager.PartialViewName, Model.Pager)
But when I move it to the top, Model.Pager.TotalPages and Model.Pager.TotalRows are both 0.
Is there any reason why this pager only works when placed at the bottom of the partial view?
Thanks!

**Comment by Muchiachio** [comment]
You need to enumerate `Grid.Rows` in some way before using the pager.
You can find more information in [an older issue](https://github.com/NonFactors/AspNetCore.Grid/issues/137).

**Comment by flgatormike** [comment]
Thanks so much. I just tried doing a Count() before calling the partial view and it works. Do you think this is a good solution, or does it make it slower by enumerating twice?

Int32 count = Model.Rows.Count();
@await Html.PartialAsync(Model.Pager.PartialViewName, Model.Pager)

**Comment by Muchiachio** [comment]
You can have one enumeration by using a temporary variable on top and passing it to the grid.
```diff
+IGridRow<Object>[] rows = Model.Rows.ToArray();

...

+@await Html.PartialAsync(Model.Pager.PartialViewName, Model.Pager)

...


-@foreach (IGridRow<Object> row in Model.Rows)
+@foreach (IGridRow<Object> row in rows)
```

**Comment by flgatormike** [comment]
Thanks!
