### ISSUE TITLE
Grid initialization

### ISSUE THREAD

**Issue by flgatormike** [NonFactors/AspNetCore.Grid#251]
Just a quick question about adding search functionality. In the documentation it shows the grid being initialized only inside the event listener, however when I do that, my grid doesn't show on the initial page load, so I have to also initialize it on document ready to make it work.

Just curious if this is the correct way to do this, initializing the grid on document ready and also every time something is typed into the search field?

Very nice work on this grid, by the way.

Thanks!!

```
    <script>
        $(document).ready(function () {
            var grid = new MvcGrid(document.querySelector('.mvc-grid'));
            document.getElementById('GridSearch').addEventListener('input', function () {
                var grid = new MvcGrid(document.querySelector('.mvc-grid'));
                grid.query.set('search', this.value);
                grid.reload();
            });
        });
    </script>


And my Razor .cshtml page:

    <input id="GridSearch" placeholder="Search..." />
    @Html.AjaxGrid(Url.Page("employees", pageHandler: "employeegrid", new { Area = "admin" }))
```

**Comment by Muchiachio** [comment]
Only the first call to `new MvcGrid` is initialization, every call after that is just reconfiguration if you need to. If you pass no configuration it does nothing, so it's safe to call many times.
