### ISSUE TITLE
Page reloading continuously, table never showing up

### ISSUE THREAD

**Issue by M-A-R-K-13** [NonFactors/AspNetCore.Grid#254]
I upgraded from previous to current version. Now page seems to reload continuously. Page title in browser tab is flashing. Table never shows up. I think I updated the code. But probably I missed something. Can you help?

**Comment by Muchiachio** [comment]
Probably didn't copy `_Grid.cshtml`?

**Comment by M-A-R-K-13** [comment]
New views and js file have been copied. The problem is still occuring. Any other idea?

**Comment by Muchiachio** [comment]
No, will need a repro :(

**Comment by M-A-R-K-13** [comment]
Okay, thanks. I will get back to this soon.

**Comment by Muchiachio** [comment]
Did you find the error?
