### ISSUE TITLE
Button column

### ISSUE THREAD

**Issue by paulinuk** [NonFactors/AspNetCore.Grid#256]
Hello

How can I add buttons that allow a row to be edited in a different view?

Paul

**Comment by Muchiachio** [comment]
[Any html](https://mvc6-grid.azurewebsites.net/encoding) can be rendered inside the grid, it's up to you to render and bind them for editing.

**Comment by paulinuk** [comment]
Are there any examples? I want to be a seperate column that passes a model property through

**Comment by Muchiachio** [comment]
I literally linked the examples..
