### ISSUE TITLE
Initial sorting not working after update to version 6.0.1

### ISSUE THREAD

**Issue by DanielStaroscik** [NonFactors/AspNetCore.Grid#257]
Hi,
after update MvcGrid from version 5.1.2 to version 6.0.1 initial sort using new method on grid column `Sortable(GridSortOrder sort)` is not working.
Previous version of this method `InitialSort(GridSortOrder sort)` was working.

**Comment by Muchiachio** [comment]
As per release notes, initial sorting was removed with 6.0.0 as it introduced too many problems and issues being created on it. Also there was no easy way to introduce multi column sorting with initial sorting present. Recommended way now is to redirect to necessary url `?sort=name asc`.
