### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by balajipitchumani** [NonFactors/AspNetCore.Grid#258]
Hi - Thanks for the huge effort in building such a nice control. apart from the sample website, is there a full docs to use the grid all features in detail.

**Comment by Muchiachio** [comment]
Sample website covers all the features and their sample usage. Is there something you can't find?

**Comment by balajipitchumani** [comment]
As I am moving from a webforms (aspx), was looking for a row event so I can format all the properties I need centrally and with complete control. Please suggest suitable sections / API, will be grateful.

**Comment by Muchiachio** [comment]
Value formatting is covered in [formatting](https://mvc6-grid.azurewebsites.net/formatting). Grid also has a row click event in [events section](https://mvc6-grid.azurewebsites.net/events) of the docs.
Not sure if this is what you need, didn't work with aspx before.
