### ISSUE TITLE
Having trouble getting a simple grid started. 

### ISSUE THREAD

**Issue by russellbolosan** [NonFactors/AspNetCore.Grid#259]
I am pretty sure I am following your instructions correctly.  But when I place the following on a partial page, I only get the Preview title showing.  Everything under that does not show.  The Model contains an enumerable property called EmployeeVehicles which contains a list of vehicles.

[code.txt](https://github.com/NonFactors/AspNetCore.Grid/files/4441188/code.txt)

**Comment by Muchiachio** [comment]
If asp net core partial doesn't render it means that there was an exception at render time.
They should be visible in your asp net core logs.

**Comment by russellbolosan** [comment]
sorry, new to this.  where would i be able to find the asp net core logs?

**Comment by Muchiachio** [comment]
You can find more information about logging in [microsoft docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging). I would also recommend learning the framework first before adding plugins on top, otherwise you might run into a lot of unrelated problems.
