### ISSUE TITLE
Issue with displaying of icons in Grid

### ISSUE THREAD

**Issue by debs1979** [NonFactors/AspNetCore.Grid#262]
I have updated from Core 2.2 to Core 3.1. Initially I had issue regarding grid grid load which I fixed taking reference from another bug reported in forum. 
Now I am facing a issue that the icons are not showing
![Capture](https://user-images.githubusercontent.com/60702995/79453304-227d8800-8007-11ea-8168-3d7f1f15423d.PNG)

The css file is like this.
![Capture1](https://user-images.githubusercontent.com/60702995/79453523-72f4e580-8007-11ea-93c5-5189c2f059ac.PNG)

Can you tell me what am i doing wrong.

**Comment by Muchiachio** [comment]
Not sure how you have that path in there, should be `../mvc-grid/fonts/grid-glyphs.woff` by default.

**Comment by debs1979** [comment]
I did that still the same issue.
![Capture3](https://user-images.githubusercontent.com/60702995/79456697-92dad800-800c-11ea-9d8d-945c67085052.PNG)

**Comment by Muchiachio** [comment]
Does the url map to the file in network tab? Or open in the browser tab?

**Comment by debs1979** [comment]
No. I am not seeing the file in the network or browser tab.

**Comment by Muchiachio** [comment]
Seems like your server is not serving/copying that file or woff in general.

**Comment by debs1979** [comment]
Is this something for the Core 3.1? I have added the UseStaticFiles in Startup.cs

**Comment by debs1979** [comment]
I got this working so closing it
