### ISSUE TITLE
MVC Grid not working in IE11

### ISSUE THREAD

**Issue by debs1979** [NonFactors/AspNetCore.Grid#263]
The application which works in chrome is not working in IE11. I am getting Syntax error for the Class MVCGrid in mvc-grid.js. Googled and found that class is not supported in IE11. Any work around?

**Comment by Muchiachio** [comment]
Version 6.x and above don't support IE11, you can either use 5.x or a transpiler.

**Comment by debs1979** [comment]
But 5.x dosen't work in Core 3.1. For that only I had to upgrade to 6.1

**Comment by Muchiachio** [comment]
It does work on core 3.1, you can checkout older web releases and test on core 3.1 it works.
