### ISSUE TITLE
table width not working

### ISSUE THREAD

**Issue by Scnck** [NonFactors/AspNetCore.Grid#264]
in my current code when the table is first initialize it's expanded beyond the parent container(table adds scroll) <DIV> but when I sort a column the table then honors the container width not sure how to fix; any ideas?  I'm unable to share current code. Thank you.

**Comment by Muchiachio** [comment]
Seems like a styling issue, maybe these [links](https://stackoverflow.com/questions/2259189/table-overflowing-outside-of-div) can help.
