### ISSUE TITLE
Can i add drop downs or check box's to grid rows

### ISSUE THREAD

**Issue by dilip1234567** [NonFactors/AspNetCore.Grid#265]
Hi,

i have the following requirement.

1) i have plain grid with the values. but now i need to add dropdown to respective column and do bulk updates.
2) can i add a check box column and select a range of rows and trigger an evant on selected rows with button click or any other option?

I have already integrated mvc6 grid but these are new requirements that i dont see in the demo. 

Thanks,

**Comment by Muchiachio** [comment]
You can add checkboxes for dropdowns the same way any other value is added, render their html and disable column encoding, [encoding](https://mvc6-grid.azurewebsites.net/encoding) page has examples of using raw strings or html helpers to do that.

Unless you need grid's row click event in particular, you could just query selected rows by using `document.querySelectorAll` and iterate/map them to ids/values you need. Grid doesn't reallyy prevent rendering anything or using normal javascript events and techniques, but we usually don't cover those in the demos.
