### ISSUE TITLE
Loading Configuration

### ISSUE THREAD

**Issue by stevebond007** [NonFactors/AspNetCore.Grid#266]
G'Day,
Must start by saying thanks for such an awesome tool! Fantastic job.
I've got the grid saving it's config in local storage in javascript as per the docos, but can't for the life of me work out how to push the config into the grid on the page load event after restoring it from localstorage.

The docos say this: .Configure(...) // Load configuration from cookie/backend/etc.

Any clarification or example most welcome.
Regards & thanks,
Steve Bond

**Comment by Muchiachio** [comment]
Ye can't really access local storage in the C# code, you might have to use cookies ☹️
I'm thinking if client side configure would be an option at all as we want to put even more configuration into that like paging/sorting/filtering/etc, but there would be no way to configure it from the client side as it would require double page reload.

**Comment by stevebond007** [comment]
Thanks for responding. I am pretty new to the whole C#/javascript game so I'm a bit confused.
I want to make so that if a user changes the config:
1. I save it in javascript using the guide provided:
document.addEventListener("gridconfigure", e => {
    const configuration = e.detail.grid.getConfiguration();
    // Save configuration to a cookie/backend/etc.
    localStorage.setItem("Configuration", JSON.stringify(configuration, null, 2));
});
When the user reloads the page I'm trying to fulfil the line .Configure(...) // Load configuration from cookie/backend/etc.
so back in javascript I:
var configuration = JSON.parse(localStorage.getItem("Configuration"));

at which point I'm stuck. As you say, it may not be possible to get that data from javascript into the Grid object.
Could you please provide some sort of sample (couple of lines) showing how YOU would achieve the aim of saving and restoring configuration state?
Maybe I've misunderstood 'cookie'?
Regards,
Steve Bond
Sorry for being a pain, I'm a bit out of my comfort zone here.

**Comment by Muchiachio** [comment]
Well local storage is not user's browser and cookie is send between the client and the server, so server has access to it while rendering the grid, you would send a configuration request, preferably with a unique grid name to load correct config
```JS
document.addEventListener("gridconfigure", e => {
    const configuration = e.detail.grid.getConfiguration();

    const response = await fetch('/saving-config-url?grid=' + e.data.grid.name, {
        method: 'POST',
        body: JSON.stringify(configuration)
    });
});
```
that url on the backend would save configuration to the response cookie or database
```C#
Response.Cookies.Append($"{grid}-configuration") = configuration;
Database.Configuration.Save(grid, configuration);
```
and then in the view you can use it like this
```C#
.Configure(JsonSerializer.Deserialize(Context.Response.Cookies.Append("my-grid-name-configuration"))
// or from database instance/viewbag/model data/etc
.Configure(Context.RequestServices.GetService<Database>().Configuration.Get("my-grid-name-configuration"))
```

**Comment by stevebond007** [comment]
@Muchiachio Many thanks, got it! Much appreciated!
