### ISSUE TITLE
Reload AjaxGrid with query set

### ISSUE THREAD

**Issue by gabri86** [NonFactors/AspNetCore.Grid#267]
Hello! How are you??

I had been using in my project an old version of the grid, in this version I could reload the grid with a certain query set as follows

	var querySet = 'name=' + name + '&description=' + description + '&dateFrom=' + dateFrom + '&dateTo=' + dateTo + 'state' + state;

	$('.mvc-grid').mvcgrid({
		requestType: 'get',
		query: querySet,
		reloadStarted: function () {
			$('.export-btn').prop('disabled', true)
			$("#btn-clean, #btn-filter").addClass("disabled");
			$("#btn-filter").html("<i class='zmdi zmdi-spinner fa-spin'></i> Processing");
		},
		reloadEnded: function () {
			$(".mvc-grid").addClass("table-responsive-md");
			$('.export-btn').prop('disabled', false)
			$("#btn-clean, #btn-filter").removeClass("disabled");
			$("#btn-filter").html("<i class='zmdi zmdi-filter-list'></i> Filter");
		},
		showLoading: true,
		reload: true
	});

For some reasons I had to upgrade to the last version of the grid and I can't figure out how I can do this in the new version, can you help me please?

Thank you very much

**Comment by Muchiachio** [comment]
API changed a bit for this, you can check the [api reference](https://mvc6-grid.azurewebsites.net/api).
It should be enough to call reload at the end
```JS
new MvcGrid(document.querySelector(".mvc-grid"), {
    query: "search=test"
}).reload();
```
There are also native [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL) and [UrlSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) instances available at `grid.url.searchParams` which you can modify to avoid encoding problems with raw strings.

**Comment by gabri86** [comment]
Great, that works like a charm! Thanks!

A few more questions...

How can I do this part??

	reloadStarted: function () {
		$('.export-btn').prop('disabled', true)
		$("#btn-clean, #btn-filter").addClass("disabled");
		$("#btn-filter").html("<i class='zmdi zmdi-spinner fa-spin'></i> Processing");
	},
	reloadEnded: function () {
		$(".mvc-grid").addClass("table-responsive-md");
		$('.export-btn').prop('disabled', false)
		$("#btn-clean, #btn-filter").removeClass("disabled");
		$("#btn-filter").html("<i class='zmdi zmdi-filter-list'></i> Filter");
	},

And, how can I obtain this?

	var sortAndOrder = $('.mvc-grid').data('mvc-grid').query;

Sorry for bother you, and thank you again!

**Comment by Muchiachio** [comment]
Grid events are invoked using bubbling `CustomEvent`. You can subscribe to them the same way you do with other DOM events, [events](https://mvc6-grid.azurewebsites.net/events) page has some examples.

Initialization returns the grid instance you can access all the data as mentioned above.
```JS
const grid = new MvcGrid(document.querySelector(".mvc-grid"));
```

**Comment by gabri86** [comment]
Thanks for the quick answer!

This works great
`const grid = new MvcGrid(document.querySelector(".mvc-grid"));`

But I have a problem with the events part.

My new code is as follows

        var grid = new MvcGrid(document.querySelector(".mvc-grid"), {
            requestType: 'get',
            query: querySet
        });

        var grid1 = document.querySelector(".mvc-grid");

        grid1.addEventListener("reloadstart", e => {
            $('.export-btn').prop('disabled', true)
            $("#btn-clean, #btn-filter").addClass("disabled");
            $("#btn-filter").html("<i class='zmdi zmdi-spinner fa-spin'></i> Processing");
        });

        grid1.addEventListener("reloadend", e => {
            $('.export-btn').prop('disabled', false)
            $("#btn-clean, #btn-filter").removeClass("disabled");
            $("#btn-filter").html("<i class='zmdi zmdi-filter-list'></i> Filter");
        });

        grid.reload()

The lines in **reloadstart** are executed as it should, but the lines in **reloadend** never get executed

What am I doing wrong?

**Comment by Muchiachio** [comment]
Ajax grid replaces the dom resulting in event binding being lost, you need to have event delegation for the ajax grid events.
