### ISSUE TITLE
Question: Is it possible to make the top row of the table 'Sticky'

### ISSUE THREAD

**Issue by stevebond007** [NonFactors/AspNetCore.Grid#269]
Hi Muchiachio,

Users are asking to have the top row stay visible when they scroll down.

Is that possible please?

Regards,

Steve Bond

**Comment by Muchiachio** [comment]
Yes, we either
- use css styling
- javascipt library for sticky elements
- or a div based partial for the grid

You can find more information on pages like [these](https://css-tricks.com/position-sticky-and-table-headers/).

**Comment by stevebond007** [comment]
Thanks Muchiachio, I'll look into it today.

Thanks again for the beautiful grid control, greatly appreciated.
