### ISSUE TITLE
Filter by date Localization Calendar

### ISSUE THREAD

**Issue by KAJOOSH** [NonFactors/AspNetCore.Grid#270]
Hello
I use the "System.Globalization.PersianCalendar" calendar. 
save it in the database as "System.Globalization.GregorianCalendar", but I use "PersianCalendar" at the time of display.
How the user does the filter based on "PersianCalendar" and searches for the equivalent in the database

**Comment by Muchiachio** [comment]
Can be implemented through [custom filter registration](https://mvc6-grid.azurewebsites.net/filter-registration).
