### ISSUE TITLE
sorting problem on exportable grid.

### ISSUE THREAD

**Issue by IstanbulFatih61** [NonFactors/AspNetCore.Grid#271]
https://mvc6-grid.azurewebsites.net/export in your example, the results dont sorting. also in my example too. is there a problem or bug  ?
![1](https://user-images.githubusercontent.com/63843654/81479594-d64fed00-922c-11ea-9f52-fc1a2e1914e3.png)
![2](https://user-images.githubusercontent.com/63843654/81479597-d94add80-922c-11ea-8d53-8926cf0c3b04.png)
![3](https://user-images.githubusercontent.com/63843654/81479599-db14a100-922c-11ea-9a65-0dae67964b6e.png)

**Comment by Muchiachio** [comment]
Yes, new version added support for multi columns sorting so sorting processor needs to be added the same way pager processor is. I fixed the documentation example.
