### ISSUE TITLE
Cannot specify the http verb anymore in 6.x

### ISSUE THREAD

**Issue by masterjs** [NonFactors/AspNetCore.Grid#272]
Hello!
You made many great changes to 6.x, including the switch to `Fetch` for your HTTP Requests. But in 5.x, we could pass a `requestType` to the `MvcGrid` if we wanted to use `POST` instead of `GET`. Is there a reason this wasn't "ported" to 6.x or its just a forgetten feature?

thank you,
JS

**Comment by Muchiachio** [comment]
It was removed. I'm thinking of adding generic options for the fetch method instead, to avoid many hand picked options in the grid. Any specific use case for the post method or just no control over the api?

**Comment by masterjs** [comment]
Hello,
If I remember well it was mainly to avoid browser caching issues and internal API conflicts with similar route names. But now that you mention this, I see no reason other valid reasons and I know there are easy ways around this. I will simply do the minor adjustments on my side to support the `GET` properly on our side.
Also if you're curious, our grid is acting like a "folder" navigation, so clicking on some nodes is resetting the grid's url (reload) to a new url and parameters. So the GET was for the initial fetch/paging and the POST was for the internal navigation in the grid.

**Comment by Muchiachio** [comment]
There is a cache buster on urls so it should be fine.
