### ISSUE TITLE
Empty template render HTML

### ISSUE THREAD

**Issue by Iztoksson** [NonFactors/AspNetCore.Grid#275]
Hi,
I was wondering if it is possible to render the Empty template/placeholder as HTML?
If I get no data I'd like to display a button saying "Add data" etc.  When I try it like this it just encodes it and displays the string verbatim:

    .Empty("<button type=\"button\" onclick=\"alert('TODO')\">Add some data</button>")

Perhaps I could use a workaround?

**Comment by Muchiachio** [comment]
Workaround would be to use Html.Raw in [_Grid.cshtml](https://github.com/NonFactors/AspNetCore.Grid/blob/v6.1.0/src/Mvc.Grid/Views/Shared/MvcGrid/_Grid.cshtml#L152). I will make it consistent with column rendering in the next release, so you can directly use html string to achieve raw rendering.

**Comment by Iztoksson** [comment]
That will be awesome, thank you!

**Comment by ivangrek** [comment]
It would be nice to be able to put a partial view
