### ISSUE TITLE
Export data grid to Excel

### ISSUE THREAD

**Issue by kevinka999** [NonFactors/AspNetCore.Grid#276]
Hello!
I'm having some troubles to export the data from the grid.
I was looking in the documentation, but here we are using the version 4.x

To avoid problems I'm not allowed to upgrade and can't find the old documentation.

Can someone help me?

**Comment by Muchiachio** [comment]
You can checkout any documentation [version](https://github.com/NonFactors/AspNetCore.Grid.Web/releases) for local view.

**Comment by kevinka999** [comment]
I didn't found nothing like this
[Actual Documentation Website](https://mvc6-grid.azurewebsites.net/export)

by the way, from this Documentation above, export data to excel had any changes? 
I'm having some troubles with the IGrid and I think is dependency

**Comment by Muchiachio** [comment]
[There is a page](https://github.com/NonFactors/AspNetCore.Grid.Web/blob/v4.1.2/Mvc.Grid.Web/Views/Grid/Export.cshtml) for it if you run it locally and navigate to export example you should be able to see it.
There might be some changes as it's 2 major versions ago.

**Comment by kevinka999** [comment]
Cool man!
I'll explore a little bit this version

Thanks, really appreciate that
