### ISSUE TITLE
Save the filter

### ISSUE THREAD

**Issue by KAJOOSH** [NonFactors/AspNetCore.Grid#277]
Hello
Do not be tired :)
How can I save the filter and then reload it when the page loads again?

**Comment by Muchiachio** [comment]
It's up to you how and where you save it, as per [example](https://mvc6-grid.azurewebsites.net/preferences).
`.Configure` accepts the configuration and `gridconfigure` event triggers on changed preferences.
So grid configure can call your backend save function and you can load it back on view rendering.

**Comment by KAJOOSH** [comment]
I've seen it before. getConfiguration'
There is no filter in this method !
I want to save the filter as a cookie

**Comment by Muchiachio** [comment]
Oh misread that, `reloadstart` and `reloadend` event should be enough to save the filter through js. Grid's url is in `grid.url` property. Another possibility is to save it on backend from `Request.Query`.

**Comment by KAJOOSH** [comment]
My code:
```
document.addEventListener("reloadstart", e => {
        var grid1 = e.detail.grid.url.search;
        Cookies.set('search1', grid1, { expires: 1 })
    });


$(document).ready(function () {
            const element = document.querySelector(".mvc-grid");
            const grid = new MvcGrid(element);
            var grid_search = grid.url.search;
            var search_Cookies = Cookies.get('search1');
            if (search_Cookies != "") {
                if (grid_search != search_Cookies) {
                    new MvcGrid(document.querySelector(".mvc-grid"), {
                        query: search_Cookies.substr(1, search_Cookies.length)
                }).reload();
                }
            }  
        });
```
When loading cookies, the page is refreshed twice
What is the optimal solution?

**Comment by Muchiachio** [comment]
Using ajax grid should not reload it twice.

**Comment by KAJOOSH** [comment]
I tested
The page was not loaded twice, but first applied without a filter and then a filter! :(

**Comment by Muchiachio** [comment]
It means you are calling `new MvcGrid()` without parameters, somewhere else.
