### ISSUE TITLE
call configure conditionally

### ISSUE THREAD

**Issue by jiangyi1985** [NonFactors/AspNetCore.Grid#279]
i'm using .Configure to load config from cookie

``` csharp
@using NonFactors.Mvc.Grid

@model IQueryable<Dashboard.Models.UriPageDto>

@{
    GridConfig gridConfig = ViewBag.gridConfig;
}

@(Html
      .Grid(Model)
      .Build(columns =>
      {
          //columns.Add(model => model.Id).Hidden();
          columns.Add(model => model.AbsoluteUri).Titled("Uri Key").Filterable(GridFilterCase.Lower);
      })
      .Configure(gridConfig)
      )
```

when first visit, the cookie is null, how should i call .Configure only when gridConfig is not null?

**Comment by Muchiachio** [comment]
You can null coalesce it into an empty config `?? new GridConfig()`.
It works because it only configures existing columns, to allow backwards compatibility.
