### ISSUE TITLE
Popup filter customization

### ISSUE THREAD

**Issue by cornelha** [NonFactors/AspNetCore.Grid#280]
I would like to display 2 date filters side by side with the operator between them but cannot see a way to do this without editing MvcGrid.js directly. Naturally this is not something I want to do as this would break compatibility with future updates. Is there currently a solution for this?

**Comment by Muchiachio** [comment]
You can create a custom datepicker with a class and register it for dates.
```JS
class MvcGridWideDateFilter extends MvcGridDateFilter {
    constructor(column) {
        super(column);

        this.cssClasses = "mvc-grid-date-filter";
    }
}
```
```JS
document.querySelectorAll(".mvc-grid").forEach(element => new MvcGrid(element, {
    filters: {
        "date": MvcGridWideDateFilter
    }
}));
```
and style it based on `mvc-grid-date-filter` class. Some of the filters already have specific classes, I will add them to all filter on next release to make it easier. It's also possible to override `renderXXX` functions the same way if you want to change html you can check current implementation for details.

**Comment by cornelha** [comment]
Awesome, thanks for the feedback. Will give it a shot
