### ISSUE TITLE
Paging controls on both top and bottom

### ISSUE THREAD

**Issue by abeardsley-vertex** [NonFactors/AspNetCore.Grid#281]
I tried modifying the `_Grid` template to render the pager buttons at both the top and the bottom.  I added this code block to the top of `_Grid`:

    @if (Model.Pager != null && Model.Rows.Any())
    {
        @await Html.PartialAsync(Model.Pager.PartialViewName, Model.Pager)
    }

The top pager appears, and the buttons work.  And the bottom pager appears as well, but when clicking the buttons nothing happens.

Is there another way to get the paging controls at both the top and bottom of the grid?

**Comment by Muchiachio** [comment]
No, basically [this](https://github.com/NonFactors/AspNetCore.Grid/blob/v6.1.0/src/Mvc.Grid/js/mvc-grid/mvc-grid.js#L536) needs to be changed to include all pager buttons in the grid partial and not in the first pager.
We will add the support for that in the next release.

**Comment by abeardsley-vertex** [comment]
I thought I had read somewhere about using jQuery to duplicate the pager?  I searches the old issues but could not find it.

**Comment by abeardsley-vertex** [comment]
I also forgot to mention this is grid version: Mvc.Grid 5.1.1.

**Comment by Muchiachio** [comment]
Yes jquery `.clone()` method can be used on page load to clone the pager with it's events. Not sure if it works though.

**Comment by abeardsley-vertex** [comment]
We upgraded to the latest version and the pagers work both on the top and bottom now.  Unfortunately the page-size dropdowns do not. It it the same symptom, the page-size dropdown at the top of the page works, the one at the bottom of the page does not.  

I have a feeling the page-size dropdowns will need a similar fix as the pager buttons did?  Also, assuming it is another javascript change, is there a way I can fix this without having to modify the `mvc-grid.js` file itself?

**Comment by Muchiachio** [comment]
Yes, it's the same problem, but harder to fix.
Adding a `change` event on both of them and updating both to the same value should be enough for a local fix.

**Comment by abeardsley-vertex** [comment]
Ok, I'll give that a shot.  Thank you.
