### ISSUE TITLE
BuildBundlerMinifier: 6.1.0 issue minimizing file

### ISSUE THREAD

**Issue by Scnck** [NonFactors/AspNetCore.Grid#282]
Not seeing issue with file but unable to BuildBundlerMinifier file.

Severity	Code	Description	Project	File	Line	Suppression State
Error	0	Expected identifier: (	MailMan	C:\Users\..\Desktop\..\..\wwwroot\js\site.min.js	68

**Comment by Muchiachio** [comment]
It probably still doesn't support some ES syntax, we dropped it long time ago for the same reasons.
