### ISSUE TITLE
I want to return to the right page with my record after the form. Sort is available. How can I do this?

### ISSUE THREAD

**Issue by KomAuras** [NonFactors/AspNetCore.Grid#283]

**Comment by Muchiachio** [comment]
Depending on the project we used one of these options
- redirect back to referrer
- persist last filter query on index
- use a dialog to create a record from the same index view
- pass grid query to the create action as a redirectUrl

**Comment by KomAuras** [comment]
I'll try to ask a question differently.
```
[HttpGet]
public ViewResult Index(int addedPersonID = 0, int page = 1, string sort = "")
{
    //Can I define the index (position) of added record in sorted IQueryable<Person> here?
    return View(Context.Set<Person>());
}
```

**Comment by Muchiachio** [comment]
If you somehow know the index in advance you can redirect to the necessary page, for example if it's 20 rows per page and your index is 24 you can redirect to the second page.
```
[HttpGet]
public ViewResult Create(...)
{
    ...

    return RedirectToAction("Index", new { page = index / 20 + 1, sort = ... });
}
```

**Comment by KomAuras** [comment]
OK, another way.
How do I can get the list of items sorted by param "sort" using your classes?
See the code above, please.

**Comment by Muchiachio** [comment]
It's only available if you build the grid on the server side, like in [export example](https://mvc6-grid.azurewebsites.net/export).
Processed rows are available in `grid.Rows`, however you will have to exclude pagination to get all the pages.
