### ISSUE TITLE
grid.reload is not a function

### ISSUE THREAD

**Issue by asafgo** [NonFactors/AspNetCore.Grid#284]
Hello,

I would like to use grid.reload() function in order to reload new data to Grid after form submit.

using Razor Pages I am using jquery.unobtrusive-ajax with form submit 
`<form method="post"
      asp-page-handler="AddNewMONumber"
      data-ajax="true"
      data-ajax-method="POST"
      data-ajax-begin="AjaxOnBegin"
      data-ajax-complete="AjaxOnComplete"
      data-ajax-update="#div_BusyIndicator">`

at AjaxOnComplete JS function I am writing 

`    function AjaxOnComplete() {
        $('#BusyIndicator').modal('hide');
        const grid = document.querySelector(".mvc-grid");
        grid.reload();
    }`

But I am getting this error
```
Uncaught TypeError: grid.reload is not a function
    at HTMLFormElement.AjaxOnComplete (MONumbers:362)
    at Object.complete (jquery.unobtrusive-ajax.min.js:16)
    at c (jquery.min.js:2)
    at Object.fireWith (jquery.min.js:2)
    at l (jquery.min.js:2)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2)
```

Thanks for any help,
AG

**Comment by Muchiachio** [comment]
Your grid variable is of a wrong type, should be `MvcGrid` not `HTMLElement`.

**Comment by asafgo** [comment]
Sorry Muchiachio I did not understood your reply.
I have followed https://mvc6-grid.azurewebsites.net/api
Can you please write for me the correct Java Script?
Thanks,
AG

**Comment by Muchiachio** [comment]
This is your code
![image](https://user-images.githubusercontent.com/6647444/88273933-9b197200-cce3-11ea-9f2b-bcfa7820584c.png)
This is api code on the page
![image](https://user-images.githubusercontent.com/6647444/88273962-a5d40700-cce3-11ea-989f-c86e48a17cf4.png)

**Comment by asafgo** [comment]
Thanks for your help, now it is working.

`        const element = document.querySelector(".mvc-grid");
        const grid = new MvcGrid(element);
        grid.reload();
`
