### ISSUE TITLE
upgrade from 4.0.3 to 6.1.0

### ISSUE THREAD

**Issue by WilliamNever** [NonFactors/AspNetCore.Grid#285]
Hi,

i need to upgrade NonFactors.Grid.Core.Mvc6 from 4.0.3 to 6.1.0 for .net core 3.1.
now, there are lots of the properties are not supported by the new version. Can you give me a upgrade guide?
such as:
data-filter-multi="@column.Filter.IsMulti", what should @column.Filter.IsMulti be in the new version?
data-filter-first-value="@column.Filter.First?.Value", the First does not support '?', and it returns a StringValues. which value should i take, the first one?

do you have the Guide for this?

Sorry, I know I should not ask the question here. but i did not find any document for my questions.

**Comment by Muchiachio** [comment]
These are used in the partial so it should just work if you updated the partial.
If you have your custom partials you can still use new version's partial as a reference.

**Comment by WilliamNever** [comment]
Thanks for your help! i have found the right way with your reference. :)
