### ISSUE TITLE
Sort icon shows a "1" when sorted ascending or decending

### ISSUE THREAD

**Issue by logiclink** [NonFactors/AspNetCore.Grid#286]
To reproduce the error go to [https://mvc6-grid.azurewebsites.net/sorting](https://mvc6-grid.azurewebsites.net/sorting) versin v6.1.0.0 and click on the name column Header. Beside the Up/Down Arrows a litte "1" is displayed.

My finding is that for @(column.Sort.Index + 1) in line 50 and 61 of _Grid.cshtml the column.Sort.Index of the sorted column is '0' whereas all other column.Sort.Index values are 'null'.

I worked around the error by css with:

```
.mvc-grid-sort span {
    display: none;
}
```

However, it would be great if the issue could be fixed.

Regards,
Marcus

**Comment by Muchiachio** [comment]
It is shown because as of 6.0.0 grid supports multi column sorting, number indicates which sort index it is.
If you don't want to see it ever, hiding it through css is appropriate solution.

**Comment by logiclink** [comment]
Many thanks for explaining the feature
