### ISSUE TITLE
Upgrade to .NetCore 3.1 breaks sorting and filtering becomes case sensitive

### ISSUE THREAD

**Issue by deanatcheq** [NonFactors/AspNetCore.Grid#287]
Hi there,

I have just upgraded .net core version from 2.1 to 3.1. All the grid loses the sorting and filter. Is there any problems with the latest nuget package? I am using following versions:

    <PackageReference Include="NonFactors.Grid.Core.Mvc6" Version="6.1.0" />
    <PackageReference Include="NonFactors.Grid.Mvc6" Version="6.1.0" />

Thanks,

**Comment by Muchiachio** [comment]
Did you update the static resources as per [installation](https://mvc6-grid.azurewebsites.net/installation) instructions?

**Comment by deanatcheq** [comment]
> Did you update the static resources as per [installation](https://mvc6-grid.azurewebsites.net/installation) instructions?

Thanks for pointing out that. I didn't. So just went through the instructions again. the js and css are updated as well. seems progressed little bit. still experienced one of this issue when I click sorting? any idea about this error?

Uncaught SyntaxError: Identifier 'MvcGrid' has already been declared

**Comment by Muchiachio** [comment]
Partials views updated too? Anything in the developer console crashing?

**Comment by jmalczak** [comment]
I believe I have the same problem. We have migrated to .net core 3.1 and not all of the filters but some of them behave this way. I think it may be connected with some of the views returning IQueryable and some of them already materialized IEnumerable.

**Comment by deanatcheq** [comment]
I followed the instructions 100%. Then I downgraded to NonFactor v5.1.2 which was the version before migration. It still works fine with v5.1.2. So, I haven't migrated to 6.1.0 yet. maybe I will try next version when it is out. still not the issue. just don't have the capacity to debug into it. 

Anyway, thanks for all help tho.

**Comment by Muchiachio** [comment]
Can't really repro on examples page which `IEnumerable<T>` or on any of our projects using `IQueryable<T>` both running 3.1.

**Comment by jmalczak** [comment]
On examples page when I filter https://mvc6-grid.azurewebsites.net/?Surname-contains=lisel it doesn't return results. Since filter is case sensitive, in previous version it wasn't. This is true when data is not pulled from database since then database engine compare values and if it's set to ci (case insensitive) then it will return Lisel when filter lisel was used.

**Comment by Muchiachio** [comment]
Yes, 6.0.0 introduced filter casing, as converting everything to lower almost always broke any indexes added on the column.
`.Filterable(GridFilterCase.Lower)` can be used on a column or on a whole grid to convert strings.

**Comment by jmalczak** [comment]
We have migrated both grid and .net core to 3.1 at the same time so this is probably coincidence. Thanks a lot, works like a charm now!
