### ISSUE TITLE
Manual processing and accessing filters.

### ISSUE THREAD

**Issue by jmalczak** [NonFactors/AspNetCore.Grid#288]
Hey

Is there away to use manual processing and access the filters passed from the client. We have some queries that doesn't translate to sql directly so I wanted to fetch one page of the data and as part of separate queries get some more data to database and at the end of my method combine this one page of the data with these additional data. Right now I can do it as described in manual processing page but we also use grid filters and I have to filter this first query to get proper page of data.

If thats possible, would there be an easy way of applying those filters as well, so I can do something like

var myPageOfData = myIqueryable
.ApplyFilters(filters)
.Skip(skip)
.Take(take)
.ToList();

then I could pull some more data from db and return result as iqueryable with different type, of course for this to work I would only set filters for columns that map 1 to 1 from my viewmodel to underlying query

Thanks

**Comment by Muchiachio** [comment]
All the filters are in request query, this is how the grid parses them. If you don't want to parse them you could get them parsed by the grid if you built it on the server side like in [export](https://mvc6-grid.azurewebsites.net/export) example and map filtering from each column.

**Comment by jmalczak** [comment]
Thanks for the reply. So if I create grid like that:

```
    IGrid<Person> grid = new Grid<Person>(repository.GetPeople());
    grid.ViewContext = new ViewContext { HttpContext = HttpContext };
    grid.Query = Request.Query;
```

but I will pass empty IEnumerable<T> since i just want to get filters, how do I get the actual filter column name, operator, value from grid? 

What I want to achieve is to have action like Index() in mvc, this action will call my service that will run query to db like

```
var userIds = users.ApplyfiltersAndPaging().Select(u => u.Id).ToList()
```

now I fetch user roles from some api lets say since it's not available in db

```
var userRolesFromApi = _apiService.GetUserRolsForUserIds(userIds)
```

now I return data to grid (this data will be Model) for the grid

```
return userIds.Join(userRolesFromApi).Select(u => new UserRoleViewModel {
Id = u.Id,
RoleName = ur.RoleName
});
```

and grid definition would be 

```
@model IQueryable<UserRoleViewModel>

@(Html
    .Grid(Model)
    .Build(columns =>
    {
        columns.Add(model => model.Id).Titled("Id");
        columns.Add(model => model.RoleName).Titled("RoleName");
    })
)
```

So if Id would be filterable, we could filter by Id and still have possibility to include rolename from external source.

**Comment by Muchiachio** [comment]
> but I will pass empty IEnumerable since i just want to get filters, how do I get the actual filter column name, operator, value from grid?

It's in the column
![image](https://user-images.githubusercontent.com/6647444/90111613-916db200-dd57-11ea-8d1b-cf99789eb992.png)

**Comment by jmalczak** [comment]
Sorry I have missed that. So to be able to parse those filter values I would have to add all matching column names first on the backend?

**Comment by Muchiachio** [comment]
Yes, or you can parse query manually. Column filter is represented as `<grid name-><column name>-<filter>=<value>`.

**Comment by jmalczak** [comment]
Cool, thanks a lot for your help!
