### ISSUE TITLE
API MvcGrid query issue

### ISSUE THREAD

**Issue by KristianFernando** [NonFactors/AspNetCore.Grid#289]
Hi guys,
I'm trying to use the query in a MvcGri API. It does not exist anymore?

That is the code:
```
var grid = new MvcGrid(document.querySelector('.mvc-grid'));
grid.requestType = 'get';
grid.query.set('param', 'abc');
```

the error is 'query is undefined'

**Comment by Muchiachio** [comment]
Newer versions of the grid only uses `grid.url` of type [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL_API#Queries). Query can be accessed and set from there.

**Comment by KristianFernando** [comment]
Thanks @Muchiachio 
I could set de parameters like this:

```
var grid = new MvcGrid(document.querySelector('.mvc-grid'));
grid.requestType = 'get';
grid.url.searchParams.append('param', 'abc');
```

is that correct?

**Comment by Muchiachio** [comment]
Should probably be `.set` instead of `.append` as append will create many values in the url.
Also request type is deprecated and always get so you don't have to set that.

**Comment by KristianFernando** [comment]
Done, thank you very much.
