### ISSUE TITLE
Export select row in grid

### ISSUE THREAD

**Issue by anantjaiswal339** [NonFactors/AspNetCore.Grid#291]
I have to export selected row of grid.
I have implemented follow by this : [export](https://mvc6-grid.azurewebsites.net/export)
but here, every time I need to retrieve from database even all of the data is already displaying in my grid.
So Is there any way to get the grid resources in controller so we can use filter on that instead of calling database?

Thanks in advance!

**Comment by Muchiachio** [comment]
Export example is showing how to access grid resources (data).
In your case though you need to pass the row id to the export function, so you can filter data based on that.

You can add id through a hidden column or a row attribute and use it on row click events.

**Comment by anantjaiswal339** [comment]
In export example: `IGrid<Person> grid = new Grid<Person>(repository.GetPeople());`
`repository.GetPeople()` are retrieving data from database.

Yes, I can pass the row id and will filter accordingly but I don't want to make a database call to get data because if there large amount of data then it will take time to retrieve from DB so If we can export on client side or can get grid resources in controller without making DB call as we already make one call on `Index` to display records.

**Comment by Muchiachio** [comment]
There is no in memory dataset on the client, as it's server side grid. But there is nothing in the grid that prevents you sending data from html into your controller. `rowclick` event can build a row data from html, but you can extract them yourself too if you need different format.

**Comment by anantjaiswal339** [comment]
Thats cool. Thanks!
Here is one suggestion: I think it will good to have a feature like JQuery export plugin to export grid data direct from the client side.

**Comment by Muchiachio** [comment]
We didn't really found any normal excel exporter, they are usually just csvs which can be created in a few ifs and value escaping.
We also didn't find a single client yet, which would want a single visible page export instead of all filtered data one, which doesn't work with client side exporters 😞

**Comment by anantjaiswal339** [comment]
OK, Thanks
