### ISSUE TITLE
Pass a parameter to Razor page OnGet when calling grid.reload();

### ISSUE THREAD

**Issue by asafgo** [NonFactors/AspNetCore.Grid#292]
Hi,
How can I pass a parameter to Razor page OnGet when calling grid.reload(); from JavaScript please?

Thanks,
AG

**Comment by Muchiachio** [comment]
You should be able to add query parameters through grid query `new Grid(element).query`.

**Comment by asafgo** [comment]
Sorry but id didn't fully understood.

My JavaScript is:

```
const element = document.querySelector(".mvc-grid");
const grid = new MvcGrid(element).query;
grid.reload();
```

My Razor Page is:
```
public async Task OnGet(string Id)
{
  //Do some work
}
```

I would like to pass for example 12345 to Id parameter at OnGet when calling grid.reload()

Thanks,
AG

**Comment by Muchiachio** [comment]
Query is of type `UrlSearchParams` you can find usage examples [here](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams#Examples).

**Comment by asafgo** [comment]
Thanks for your help!
