### ISSUE TITLE
Empty text now encoded by default

### ISSUE THREAD

**Issue by jmalczak** [NonFactors/AspNetCore.Grid#293]
Hi

I have noticed that after latest update Empty text is encoded by default. We use unicode characters for empty text and now it looks like that:

```
Nie znaleziono zam&#xF3;wie&#x144;
```

and before it was

```
Nie znaleziono zamówień
```

**Comment by jmalczak** [comment]
Sorry, never mind. After writing this issue I have noticed changes in cshtml.

**Comment by Muchiachio** [comment]
Yes, we tried to make it as non breaking as possible for #247 
If you are using `Empty("Nie znaleziono zamówień")` it should still work.

**Comment by jmalczak** [comment]
Yeah, sorry I have missed changes in cshtml so I have updated just dlls. After updating partials everything works great!
