### ISSUE TITLE
Translate the displayname with shared resource

### ISSUE THREAD

**Issue by Mapel** [NonFactors/AspNetCore.Grid#297]
Hi,

adding the column without using '.Titeld("Title")' the displayname of the property is used, but it is not translated, if a shared resource is implemented (https://damienbod.com/2017/11/01/shared-localization-in-asp-net-core-mvc/).

Is is possible to use that with your AspNetCore Grid?

Thanks

**Comment by Muchiachio** [comment]
It can be used, but you will have to write your own extension for title or for adding the column similar to [this](https://github.com/NonFactors/AspNetCore.Template/blob/3cff4f503665a822edac3e8e3aca529cab780b72/src/MvcTemplate.Components/Extensions/MvcGrid/MvcGridExtensions.cs#L71-L78).
```C#
public static IGridColumn<T, TProperty> AddProperty<T, TProperty>(
    this IGridColumnsOf<T> columns, Expression<Func<T, TProperty>> expression)
{
    return columns.Add(expression).Titled(Resource.ForProperty(expression));
}
```
where `Resource.ForProperty` is your function for getting the shared resource.
