### ISSUE TITLE
Pass filter value on first load of the grid.

### ISSUE THREAD

**Issue by gandhiarpit** [NonFactors/AspNetCore.Grid#298]
Hi,

I have an ajax grid on a edit/create view with other form elements and few filters.
` 
            @Html.AjaxGrid(Url.Action("Create"), Model.Users)
`

I want to pass the Id on first load to the action method, but can't seem to find a way to do it. I have seen the global search functionality which I have used it when an event happens on the page/view and set the URLParams and reload grid. 

But what event or how do I send the id back to action method during the ajax call. Is there any js event I can capture and set the value before the ajax call is made to load the grid?

`
        public async Task<IActionResult> Index(string Id)
        {
            var vm = new ViewModel();

            try
            {
                if (HttpContext.Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                {
                    if (!string.IsNullOrEmpty(Id))
                    {
                        var result = await GetRecords(id);
                        return PartialView("_List", result);
                    }
                    else
                    {
                        return PartialView("_List", new List<ListViewModel>());
                    }
                }
                else
                {
                    vm.Id = Id;
                }
            }
            catch (Exception ex)
            {
                _logger.LogError($"Controller.Index: {ex.Message}");
            }

            return View(vm);
        }
`

`
  $("#btnFilters").click(function () {
            var temp = $('form').serialize();
            const grid = new MvcGrid(document.querySelector(".mvc-grid"));

            grid.url.searchParams.set("search", temp);
            grid.reload();
        });
`

Ps: Sorry for the formatting issue. Can't seem to make it work properly.

**Comment by Muchiachio** [comment]
You can generate a different url here `Url.Action("Create")`.

**Comment by gandhiarpit** [comment]
> You can generate a different url here `Url.Action("Create")`.

Thank You. Totally forgot about that bit. Got it working now.

Can the data bit below have a complex object or json object in below code. Got some filters (dropdowns) outside the grid which I want to pass to filter the grid.

`
   const grid = new MvcGrid(document.querySelector(".mvc-grid"));
            grid.url.searchParams.set("search", data);
`

**Comment by Muchiachio** [comment]
Grid url is of type [UrlSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams). I don't think it support merging a complex object.
But you can as easily iterate over your object and set the values in on foreach loop.

**Comment by gandhiarpit** [comment]
Ok. For the moment I solved it using form serialize and passed on to backend. Will sort out the fields in the backend.

`
            var data = $('form').serialize();
const grid = new MvcGrid(document.querySelector(".mvc-grid"));
            grid.url.searchParams.set("search", data);
`
