### ISSUE TITLE
MVC Grid version 5.x not working on ASP.NET Core 3.1

### ISSUE THREAD

**Issue by hooliday** [NonFactors/AspNetCore.Grid#299]
Hi, I worked with your grid 6.x without any issues, but because compatibility of IE11 I need use 5.x but I have problem with references in Shared folder, any work around?

**Comment by Muchiachio** [comment]
Version 5 does work on net core 3, maybe you didn't update razor views to match version 5?

**Comment by hooliday** [comment]
I tried to start a new application asp net core 3.1, install package NonFactors.Grid.Core.Mvc5 -Version 7.1.3, add content file from NonFactors.Grid.Mvc5 and then include style, script and inicialization to _layout but still have problem with references from _grid.cshtml with @using System.Web.Mvc;

**Comment by Muchiachio** [comment]
`NonFactors.Grid.Core.Mvc5` is a mvc5 package and not aspnet core version.
Aspnet core version is `NonFactors.Grid.Mvc6`, installation instruction [here](https://mvc6-grid.azurewebsites.net/).

**Comment by hooliday** [comment]
This works fine (for chromium), but incompatible for IE11, so what is the next step?

**Comment by Muchiachio** [comment]
Core's `v5.1.2` was the last version which had IE compatibility, I thought you are trying to downgrade to that version?
I'm confused by now what you are trying to achieve. Other option is to use js transpiler on the newest version which works too.

**Comment by hooliday** [comment]
Now I have downgraded version NonFactors.Grid.Core.Mvc5 to 5.1.2, used content files from the same version (installation instruction). Then grid works in Chrome, Edge, but IE11 has syntax error with document.querySelectorAll(".mvc-grid").forEach(element => new MvcGrid(element));

**Comment by Muchiachio** [comment]
This is your own code not grid's.

**Comment by hooliday** [comment]
This is the last step in "installation steps"

**Comment by hooliday** [comment]
I set up a repository for a better description here https://github.com/hooliday/GridIE11

**Comment by Muchiachio** [comment]
Again, this is your initialization code, it doesn't work because you are copying 6.X example and not 5.X.
You can initialize it any way you want, for example like this
```JS
[].forEach.call(document.getElementsByClassName("mvc-grid"), function (element) {
   new MvcGrid(element);
});
```
or like this
```JS
[].forEach.call(document.querySelectorAll("mvc-grid"), function (element) {
   new MvcGrid(element);
});
```
or like that
```JS
var elements = document.getElementsByClassName("mvc-grid");
for (var i = 0; i < elements.length; i++) {
    new MvcGrid(elements[i]);
}
```
or maybe this
```JS
new MvcGrid(document.getElementsByClassName("mvc-grid")[0]);
```
or this
```JS
new MvcGrid(document.querySelectorAll(".mvc-grid")[0]);
```
or that
```JS
new MvcGrid(document.querySelector(".mvc-grid"));
```
or with jquery
```JS
new MvcGrid($(".mvc-grid")[0]);
```
or with each
```JS
$(".mvc-grid").each((i, element) => {
    new MvcGrid(element);
});
```
or any other way which worked in 2013.

**Comment by hooliday** [comment]
It works, I appreciate your help.
