### ISSUE TITLE
Export filtering data, problem with query string parameters (grid filters)

### ISSUE THREAD

**Issue by hooliday** [NonFactors/AspNetCore.Grid#301]
Hello, Im trying export filtered grid data, but I cant access to names and their values of filters (to set query string), any way to do it?

**Comment by hooliday** [comment]
grid.Reload();

**Comment by Muchiachio** [comment]
You are probably using ajax grid which uses inernal `new MvcGrid(...).query` property preserve the query.

**Comment by hooliday** [comment]
I thought I had solved the problem, but unfortunately not. I use "grid global search" implementation and grid filters and Im trying export filtered data.

**Comment by Muchiachio** [comment]
So, what is not working in the grid? You have the ajax grid, you can get the url and 
- You are using global search implementation which seems to work [here](https://mvc6-grid.azurewebsites.net/global-search).
- Exporting by given the filter seems to work [too](https://mvc6-grid.azurewebsites.net/export?Age-equals=21).

You can also traverse the whole grid object for data if needed or use the source on github for debugging.

**Comment by hooliday** [comment]
Here is my example, maybe it will be clearly. https://github.com/hooliday/Example
