### ISSUE TITLE
Question: Find the column

### ISSUE THREAD

**Issue by KAJOOSH** [NonFactors/AspNetCore.Grid#302]
How do we know which column is clicked from the row?

Is it possible with this function?
```
document.addEventListener('rowclick', function (e) {
});
```

**Comment by Muchiachio** [comment]
Event details contains the original click event. I'm guessing that it should have the original cell clicked, not sure if it's enough to determine the column though. Would be easier to bind a column class and add your own handler, if it's only one specific column.

**Comment by KAJOOSH** [comment]
Do you think the following parameter can be used correctly for this issue?
`rowclick.detail.originalEvent.target.offsetParent.className`

**Comment by Muchiachio** [comment]
I prefer using `target.closest("td").classList.contains("x")` to avoid dynamic nested content issues.
