### ISSUE TITLE
Sort By Multiple columns 

### ISSUE THREAD

**Issue by minaghaly** [NonFactors/AspNetCore.Grid#303]
Hey,

I couldn't find the following TheSortBy expression in AspNetCore.Grid version.

Columns.Add(x=>x.Date).Sortable(true).ThenSortBy(x=>x.Time);

Do you have any alternatives?

The main issue that I need to add a tie-breaker order expression because sometimes the returned list for the second page for example has already some items from the first page.

**Comment by Muchiachio** [comment]
There are no initial sort options anymore. There are few ways you can go about it
- Return already sorted data for the initial grid load.
- Let the users sort it using multi sorting feature (ctrl/shift clicks).
- Redirect to initial sort url `?sort=Date asc,Time asc`, instead of empty one.

**Comment by minaghaly** [comment]
Hey Muchiachio, 

The first option will not work fine, because I still need the user to have the sorting options, If I returned the data already sorted, so the user can't sort them or the user required sorting will come after the default sorting.

The second option is valid, but still, it is a bug in my system; so we can't let the user decide to fix it or not.

Actually, I will go to the third option, I will always add a unique column to sorting expression to make sure that the result will be deterministic.

Thank you.
