### ISSUE TITLE
RazorPage add <a asp-page="./Review/Index" asp-route-id="model.Id">Review </a> in a column

### ISSUE THREAD

**Issue by Lerseb** [NonFactors/AspNetCore.Grid#304]
Hi everyone,
I am discovering AspNetCore.Grid and it is really great.
I am struggling when I want to add an hyperlink specifying a route.
I am using RazorPages so the snippet below doesn't work.
columns.Add(model => Html.ActionLink("Delete", "Delete", new { id = model.Id }));

By the way, I use to have multiple hyperlinks in the same last column of the grid (Edit Delete ...). Is it possible to do that in AspNetCore.grid?

Thanks for your help.
Best regards
Sebastien

**Comment by Muchiachio** [comment]
> I am using RazorPages so the snippet below doesn't work.

I believe razor pages uses different functions for page link generation.
`Html.ForPage` or similar maybe? There should be examples in your project.

> By the way, I use to have multiple hyperlinks in the same last column of the grid (Edit Delete ...). Is it possible to do that in AspNetCore.grid?

It's the same question as `How do you put two html contents into one in variable asp net?`
We usually use `HtmlContentBuilder`, but you can also you any other method to create a single html for asp to consume.
