### ISSUE TITLE
MVC Grid v5.1.2 - Named sort columns

### ISSUE THREAD

**Issue by coxp** [NonFactors/AspNetCore.Grid#307]
Is there any way to disable the user friendly url column names when using v5.1.2? We name all our columns using Named but this is still overridden by the user friendly url column name.

**Comment by Muchiachio** [comment]
I can't repro on `columns.Add(model => model.MaritalStatus).Named("Marital");`
It generates url using `marital-equals=1` instead of `marital-status-equals=1`.

**Comment by coxp** [comment]
Sorry, should've put an example. `columns.Add(model => model.OfficialName).Named("OfficialName")` in v.3.4.0 generated the sort column name `OfficialName` but in v5.1.2 generates `official-name`. We use the grid in quite a few places so I was hoping that I could disable this new behaviour rather than changing the back-end code everywhere.

**Comment by Muchiachio** [comment]
Two options
- upgrade to 6.0.0+ which doesn't have friendly url conversion at all.
- create your own `Named` extension to set the name directly.

```C#
public static IGridColumn<T, TValue> MyNamed<T, TValue>(this IGridColumn<T, TValue> column, String name)
{
    column.Name = name.Trim();

    return column;
}
```

**Comment by coxp** [comment]
Okay, thanks for your help. I'll implement the extension as I'm not sure we can drop IE11 support at the moment :thumbsup:
