### ISSUE TITLE
Filtering issue with multiple grids

### ISSUE THREAD

**Issue by zfregin** [NonFactors/AspNetCore.Grid#310]
Hello,

I was testing out rendering multiple grids on the same page like your example here: http://mvc-grid.azurewebsites.net/Grid/Multiple, however I seem to be having an issue with the column filter selection. The second grid's column filter popup does not appear at all, but the first grid has no issue filtering. After each filter selection on the first grid, the result also appears to return a duplicate of the 2nd grid, so that a 3rd grid is rendered, then 4th, and so on with each selection. I am using a partial view for the grid and tried rendering both grids in the same partial with the HTML Helper as well as a separate, nested partial for the second grid, but the same behavior is observed. I gave both grids unique Grid names and ID's and I tried using the same model for data as well as two separate IQueryables in the model given to the partial that were then respectively provided to the .Grid helpers/nested partial. I also verified that one request is being made for the filter selection.

I am not sure what I could be doing wrong, do you have any guidance for this issue?

Thanks

**Comment by Muchiachio** [comment]
Grid duplication usually happens if a grid partial includes more than one root element other than the `.mvc-grid`.
You should be able to trace it back using JS debugger, why grids are duplicating or not binding the events.
